version: '3.8'

services:
  backend:
    build:
      context: ./backend
      args:
        NODE_ENV: development
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: node server.js

  frontend:
    build:
      context: ./frontend/myapp
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/myapp:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - backend